
services:
  db:
    image: postgres:16.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: p_finanzas
      POSTGRES_PASSWORD: 08653456789olASDT
      POSTGRES_DB: finanzas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: fintri_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://p_finanzas:08653456789olASDT@db:5432/finanzas
    restart: always

volumes:
  db_data:
